### ISSUE TITLE
pre-trained checkpoint with 4M data 

### ISSUE THREAD

**Issue by jaeseokbyun** [xinyu1205/Tag2Text#3]
First of all, thanks for sharing great work!

I'm trying to use your pre-trained network for my research.
But could you also share pre-trained networks with a 4M dataset (without CC12M)? 
(If possible, please share both ViT and Swin-transformer versions)

**Comment by xinyu1205** [comment]
Thank you for showing interest in our work, it is truly an honor to have your attention. 
Personally, I would love to open source all the pre-trained models right away, but they are saved internally within our company, and opening them up involves  a complex approval process that requires sufficient justification. For instance, opening up 14M Tag2Text model for showcasing the huggingface demo. This has resulted in me not being able to immediately open source all the pre-trained models.
If it's convenient for you, could you provide more information on the need for the 4M Tag2Text models? Given that we have already opened source 14M Tag2Text model. I really hope you can understand the situation, and thank you once again for your attention to our work!
Best wishes!

**Comment by spacewalkingninja** [comment]
I really would need this to run it on a lower memory GPU, as I also got no money to buy new gpu or rent a gpu. I am using a 1070 8gb vam gpu and the 14m model is too big for some use cases.

**Comment by spacewalkingninja** [comment]
thanks for being one of the good guys that want to relkease models opensource rightaway, will be very thankful when 4m model is released

**Comment by spacewalkingninja** [comment]
take back my words, prolly won't need it actually, got around to optimizing my code better with batching!

**Comment by xinyu1205** [comment]
> take back my words, prolly won't need it actually, got around to optimizing my code better with batching!

Thank you for your attention. Your GPU should be able to run Tag2Text, because Tag2Text can also inference in a CPU environment. Moreover, there is no difference in model size between 14M and 4M, except for the pretraining dataset.
Hope you enjoy using Tag2Text, best wishes!
