### ISSUE TITLE
Training code and datasets

### ISSUE THREAD

**Issue by chaos1992** [xinyu1205/Tag2Text#5]
Thanks for your wonderful work. When can you release the training code and datasets? Can't wait to use it😊

**Comment by xinyu1205** [comment]
Thank you for your attention to our work! Personally, I would love to open source the training code and datasets right away, but there are two reasons why I am unable to immediately open source them: 
1. Tag2Text is still in the preprint version, and we are constantly improving it;
2. The code and datasets are saved internally within our company, and opening them up involves a complex approval process that requires sufficient justification.
I really hope you can understand the situation. We expect to fully open source the training code and datasets by 3-4 months at the latest. Thank you once again for your attention to our work!
Best wishes!
