### ISSUE TITLE
how to modify the results to be displayed in Chinese?

### ISSUE THREAD

**Issue by gaoyong06** [xinyu1205/Tag2Text#7]
Hello, thank you for your work. May I ask how to modify the results to be displayed in Chinese? I change the bert-base-uncased file in init_tokenizer and change the Cased file to bert-base-chinese. The result is wrong

**Comment by xinyu1205** [comment]
感谢您的关注！虽然Tag2Text与text/tag的交互模块是基于bert的预训练参数，但是由于模型在新的多模态数据上进行了训练，这些模块的参数进行了改变，因此恐怕无法通过直接将tokenizer等模块转换为中文版本来获得中文的输出。
唯一比较好的办法可能就是通过翻译软件或GPT等应用，得到英文输出后转换为中文。
祝好！

**Comment by gaoyong06** [comment]
好勒，多谢多谢
